"""ADD User Table

Revision ID: 2e60a8b51c4b
Revises: b9b329389042
Create Date: 2022-07-18 18:19:18.506843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision = '2e60a8b51c4b'
down_revision = 'b9b329389042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', PasswordType(schemes=['pbkdf2_sha512', 'md5_crypt'],
                                       deprecated=['md5_crypt']), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
